### PR TITLE
Reuse UDP socket

### PR DESCRIPTION
**Pull request by nastevens**
(Note that this PR requires the changes in #10 and #11. I have merged them into this branch for now, but if you prefer a different strategy, such as a rebase, just let me know and I can rebase when the other two PRs are merged.)

Previously, the code created a new UDP socket for each metric sent. This incurs a significant overhead per metric sent, as can be seen in the following comparisons.

This commit moves the UDP socket open into the constructor and reuses the same socket for each metric sent, significantly improving per-metric send times.

Comparison using cargo-benchcmp:

    name                    new_socket ns/iter  reuse_socket ns/iter  diff ns/iter   diff %
    bench::bench_decr       190,423             3,345                     -187,078  -98.24%
    bench::bench_event      146,713             3,614                     -143,099  -97.54%
    bench::bench_gauge      153,778             3,507                     -150,271  -97.72%
    bench::bench_histogram  178,040             3,507                     -174,533  -98.03%
    bench::bench_incr       181,901             3,374                     -178,527  -98.15%
    bench::bench_set        163,280             3,552                     -159,728  -97.82%
    bench::bench_timing     142,588             3,420                     -139,168  -97.60%

### CODE REVIEW

**Comment by mcasper** [comment]
Thanks so much for the contributions @nastevens! This strategy is totally fine, once we get #11 merged in you can just rebase this on top of master and we'll get it in

**Comment by mcasper** [comment]
Ok, #11 and #10 have both been merged, so you can rebase this over master and it should be good to go

**Comment by nastevens** [comment]
> Ok, #11 and #10 have both been merged, so you can rebase this over master and it should be good to go

Done!

**Comment by mcasper** [comment]
Awesome, published 0.2!

**Pull request merged**
